### ISSUE TITLE
Video Player widget is not recorded

### ISSUE THREAD

**Issue by alpeshshiyal** [Baseflow/screenrecorder#34]
i have used screen_recorder: ^0.0.3 version for recording my widget but video player widget is recorded as white screen and content of video not visible.

screen_recorder: ^0.0.3 
video_player: ^2.4.10

**Comment by ueman** [comment]
This is a known issue of Flutter as mentioned in the readme of this library:

> Platform views are invisible in screenshots (like webview or Google Maps). For further details, see this [Flutter issue](https://github.com/flutter/flutter/issues/25306) and [this issue](https://github.com/flutter/flutter/issues/102866). Please give a 👍 to those issues in order to raise awareness and the prio of those issues.
