### ISSUE TITLE
Because every version of screen_recorder depends on image ^3.0.2 

### ISSUE THREAD

**Issue by SittiphanSittisak** [Baseflow/screenrecorder#39]
I must use the latest version of the image package.
Can you update this package to use the image package with the newest version?

**Comment by martijn00** [comment]
Can you make a PR to update this?

**Comment by SittiphanSittisak** [comment]
Hi, I don't have experience with this.
I tried to copy your source code include: 
```
flutter_screen_recording_platform_interface.dart
flutter_screen_recording_web.dart
get_display_media.dart
method_channel_flutter_screen_recording.dart
```
Then I tried to use this with the direct `WebFlutterScreenRecording` class.
There are not any errors with using [image package](https://pub.dev/packages/image) and I don't find any image package used in your code, only the `quiver`, `open_file`, and `plugin_platform_interface` packages are used.
(Maybe I copied not all code.)

This is my error when importing screen_recorder with image packages.
```
Because every version of screen_recorder depends on image ^3.0.2 and flutter_test_recording depends on image ^4.0.17, screen_recorder is forbidden.
So, because flutter_test_recording depends on screen_recorder ^0.2.0, version solving failed.
```
