### ISSUE TITLE
Headless recording of widgets

### ISSUE THREAD

**Issue by ueman** [Baseflow/screenrecorder#41]
Inspired by the following https://github.com/ABausG/home_widget/blob/b7663c12eea36daa1033fe5d87f513819d1e2ea5/lib/home_widget.dart#L114:L187 

It may be possible to render widgets in a headless mode. This could enable a more ergonomic API to record widgets.

**Comment by TimHoogstrate** [comment]
Dear @ueman,

Thanks for reaching out! I am not so familiar with the plugin, so can you elaborate a bit more on your issue? Can you for example explain what is wrong with the current api and what your enhancement would improve? Can you also for example give some examples why you would use it? If possible we would encourage you to prepare a PR with the suggested enhancement and perhaps also some steps to test. Looking forward to your reply.

Kind regards,
